type BookMap = {
  [p: string]: string;
};

export default {
  "Genesis": "Gen",
  "Gen": "Gen",
  "Exodus": "Exod",
  "Ex": "Exod",
  "Exod": "Exod",
  "Leviticus": "Lev",
  "Lev": "Lev",
  "Numbers": "Num",
  "Num": "Num",
  "Deuteronomy": "Deut",
  "Deut": "Deut",
  "Joshua": "Josh",
  "Josh": "Josh",
  "Judges": "Judg",
  "Judg": "Judg",
  "Ruth": "Ruth",

  "[1|I]\\s?Samuel": "1Sam",
  "[1|I]\\s?Sam": "1Sam",

  "[2|II]\\s?Samuel": "2Sam",
  "[2|II]\\s?Sam": "2Sam",

  "[1|I]\\s?Kings": "1Kgs",
  "[1|I]\\s?Kgs": "1Kgs",
  "[2|II]\\s?Kings": "2Kgs",
  "[2|II]\\s?Kgs": "2Kgs",

  "[1|I]\\s?Chronicles": "1Chr",
  "[1|I]\\s?Chr": "1Chr",
  "[2|II]\\s?Chronicles": "2Chr",
  "[2|II]\\s?Chr": "2Chr",
  "Ezra": "Ezra",
  "Nehemiah": "Neh",
  "Neh": "Neh",

  "Esther": "Esth",
  "Esth": "Esth",
  "Est": "Esth",

  "Job": "Job",
  "Psalms": "Ps",
  "Psalm": "Ps",
  "Ps": "Ps",

  "Proverbs": "Prov",
  "Prov": "Prov",
  "Pro": "Prov",

  "Ecclesiastes": "Eccl",
  "Eccl": "Eccl",
  "Song of Solomon": "Song",
  "Song": "Song",
  "Songs of Solomon": "Song",
  "Isaiah": "Isa",
  "Isa": "Isa",
  "Jeremiah": "Jer",
  "Jer": "Jer",
  "Lamentations": "Lam",
  "Lam": "Lam",
  "Ezekiel": "Ezek",
  "Ez": "Ezek",
  "Ezek": "Ezek",
  "Daniel": "Dan",
  "Dan": "Dan",
  "Hosea": "Hos",
  "Hos": "Hos",
  "Joel": "Joel",
  "Amos": "Amos",

  "Obadiah": "Obad",
  "Obab": "Obad",

  "Jonah": "Jonah",
  "Jon": "Jonah",
  "Micah": "Mic",
  "Mic": "Mic",
  "Nahum": "Nah",
  "Nah": "Nah",
  "Habakkuk": "Hab",
  "Hab": "Hab",
  "Zephaniah": "Zeph",
  "Zeph": "Zeph",
  "Haggai": "Hag",
  "Hag": "Hag",
  "Zechariah": "Zech",
  "Zech": "Zech",
  "Malachi": "Mal",
  "Mal": "Mal",
  "Matthew": "Matt",
  "Matt": "Matt",
  "Mark": "Mark",
  "Luke": "Luke",
  "Lu": "Luke",
  "John": "John",
  "Jn": "John",
  "Acts": "Acts",
  "Romans": "Rom",
  "Rom": "Rom",
  "[1|I]\\s?Corinthians": "1Cor",
  "[1|I]\\s?Cor": "1Cor",
  "[2|II]\\s?Corinthians": "2Cor",
  "[2|II]\\s?Cor": "2Cor",
  "Galatians": "Gal",
  "Gal": "Gal",
  "Ephesians": "Eph",
  "Eph": "Eph",
  "Philippians": "Phil",
  "Phil": "Phil",
  "Colossians": "Col",
  "Col": "Col",

  "[1|I]\\s?Thessalonians": "1Thess",
  "[1|I]\\s?Thess": "1Thess",
  "[2|II]\\s?Thessalonians": "2Thess",
  "[2|II]\\s?Thess": "2Thess",

  "[1|I]\\s?Tim": "1Tim",
  "[1|I]\\s?Timothy": "1Tim",
  "[1|I]\\s?Ti": "1Tim",

  "[2|II]\\s?Timothy": "2Tim",
  "[2|II]\\s?Tim": "2Tim",
  "[2|II]\\s?Ti": "2Tim",

  "Titus": "Titus",
  "Philemon": "Phlm",
  "Hebrews": "Heb",
  "Heb": "Heb",
  "James": "Jas",
  "[1|I]\\s?Peter": "1Pet",
  "[1|I]\\s?Pet": "1Pet",
  "[2|II]\\s?Peter": "2Pet",
  "[2|II]\\s?Pet": "2Pet",

  "[1|I]\\s?John": "1John",
  "[2|II]\\s?John": "2John",
  "[3|III]\\s?John": "3John",
  "Jude": "Jude",
  "Revelation": "Rev",
  "Rev": "Rev",

  "1Sam": "1Sam",
  "2Sam": "2Sam",
  "1Kgs": "1Kgs",
  "2Kgs": "2Kgs",
  "1Chr": "1Chr",
  "2Chr": "2Chr",

  "Sng": 'Song',
  Obad: "Obad",
  "1Cor": "1Cor",
  "2Cor": "2Cor",
  "1Thess": "1Thess",
  "2Thess": "2Thess",
  "1Tim": "1Tim",
  "2Tim": "2Tim",
  Phlm: "Phlm",
  Jas: "Jas",
  "1Pet": "1Pet",
  "2Pet": "2Pet",
  "1John": "1John",
  "2John": "2John",
  "3John": "3John",
  // SPANISH

  "Génesis":"Gen",
  "Éxodo":"Exod",
  "Levítico":"Lev",
  "Números":"Num",
  "Deuteronomio":"Duet",
  "Josué":"Josh",
  "Jueces":"Judg",
  "Rut":"Ruth",
  "[1|I]\\s?Reyes":"1Kgs",
  "[2|II]\\s?Reyes":"2Kgs",
  "[1|I]\\s?Crónicas":"1Chr",
  "[2|II]\\s?Crónicas":"2Chr",
  "Esdras":"Ezra",
  "Nehemías":"Neh",
  "Ester":"Esth",
  "Salmos":"Ps",
  "Proverbios":"Prov",
  "Eclesiastés":"Eccl",
  "Cantares":"Song",
  "Isaías":"Isa",
  "Jeremías":"Jer",
  "Lamentaciones":"Lam",
  "Ezequiel":"Ezek",
  "Oseas":"Hos",
  "Amós":"Amos",
  "Abdías":"Obad",
  "Jonás":"Jonah",
  "Miqueas":"Mic",
  "Nahúm":"Nah",
  "Habacuc":"Hab",
  "Sofonías":"Zeph",
  "Hageo":"Hag",
  "Zacarías":"Zech",
  "Malaquías":"Mal",
  "Mateo":"Matt",
  "Marcos":"Mark",
  "Lucas":"Luke",
  "Juan":"John",
  "Hechos":"Acts",
  "Romanos":"Rom",
  "[1|I]\\s?Corintios":"1Cor",
  "[2|II]\\s?Corintios":"2Cor",
  "Gálatas":"Gal",
  "Efesios":"Eph",
  "Filipenses":"Phil",
  "Colosenses":"Col",
  "[1|I]\\s?Tesalonicenses":"1Thess",
  "[2|II]\\s?Tesalonicenses":"2Thess",
  "[1|I]\\s?Timoteo":"1Tim",
  "[2|II]\\s?Timoteo":"2Tim",
  "Tito":"Titus",
  "Filemón":"Phlm",
  "Hebreos":"Heb",
  "Santiago":"Jas",
  "[1|I]\\s?Pedro":"1Pet",
  "[2|II]\\s?Pedro":"2Pet",
  "[1|I]\\s?Juan":"1John",
  "[2|II]\\s?Juan":"2John",
  "[3|III]\\s?Juan":"3John",
  "Judas":"Jude",
  "Apocalipsis":"Rev",

  "Gén":"Gen",
  "Gn":"Gen",
  "Éxod":"Exod",
  "Éx":"Exod",
  "Lv":"Lev",
  "Núm":"Num",
  "Nm":"Num",
  "Dt":"Deut",
  "Jos":"Josh",
  "Jue":"Judg",
  "Jc":"Judg",
  "Rt":"Ruth",
  "[1|I]\\s?Sm":"1Sam",
  "[2|II]\\s?Sm":"2Sam",
  "[1|I]\\s?Rey":"1Kgs",
  "[1|I]\\s?Re":"1Kgs",
  "[2|II]\\s?Rey":"2Kgs",
  "[2|II]\\s?Re":"2Kgs",
  "[1|I]\\s?Cró":"1Chr",
  "[1|I]\\s?Cr":"1Chr",
  "[2|II]\\s?Cró":"2Chr",
  "[2|II]\\s?Cr":"2Chr",
  "Ne":"Neh",

  "Sal":"Ps",

  "Pr":"Prov",
  "Ecl":"Eccl",
  "Ec":"Eccl",
  "Cant":"Song",
  "Sab":"Eccl",
  "Sir":"Eccl",
  "Si↵o Eclo":"Eccl",
  "Is":"Isa",
  "Jr":"Jer",
  "Ezeq":"Ezek",

  "Dn":"Dan",
  "Os":"Hos",
  "Jl":"Joel",
  "Am":"Amos",
  "Abd":"Obad",

  "Miq":"Mic",
  "Mi":"Mic",
  "Na":"Nah",
  "Sof":"Zeph",
  "So":"Zeph",
  "Ag":"Hag",
  "Zac":"Zech",
  "Za":"Zech",
  "Mat":"Matt",
  "Mt":"Matt",
  "Mar":"Mark",
  "Mc":"Mark",
  "Luc":"Luke",
  "Lc":"Luke",

  "Hech":"Acts",
  "Hch":"Acts",
  "[1|I]\\s?Co":"1Cor",
  "[2|II]\\s?Co":"2Cor",
  "Gál":"Gal",
  "Efes":"Eph",
  "Ef":"Eph",
  "Fil":"Phil",
  "Flp":"Phil",
  "[1|I]\\s?Tes":"1Thess",
  "[2|II]\\s?Tes":"2Thess",
  "Tit":"Titus",
  "Ti":"Titus",
  "Filem":"Phlm",
  "Flm":"Phlm",
  // TODO: WHERE"S Hebrew
  "Sant":"Jas",
  "Stgo":"Jas",
  "St":"Jas",
  "[1|I]\\s?Pe":"1Pet",
  "[2|II]\\s?Pe":"2Pet",
  "[1|I]\\s?Jn":"1John",
  "[2|II]\\s?Jn":"2John",
  "[3|III] Jn":"3John",
  "Jds":"Jude",
  "Jud":"Jude",
  "Apoc":"Rev",
  "Ap":"Rev"
} as BookMap;
